### ISSUE TITLE
There are some thing wrong in Core Plot Gallery Example ?

### ISSUE THREAD

**Issue by 870021840** [core-plot/core-plot#171]
Xcode6.3 ,*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs'

**Comment by alcamla** [comment]
I have the same issue. It occurs when selecting any demo from the tableView.

**Comment by eskroch** [comment]
Device or simulator? iPhone or iPad? iOS version? Core Plot version?

**Comment by alcamla** [comment]
Using:
-CorePlot 1.5.1
-iPhone and Simulator
-iOS 8.3
-Xcode 6.3
 
The error I get after selecting any row:
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs'

I also tried with core-plot release-2.0,  getting  the same error when deploying to simulator. When I tried to deploy to iPhone iOS 8.3 using release-2.0, I get this error:

dyld: Library not loaded: @rpath/CorePlot_iOS.framework/CorePlot_iOS
  Referenced from: /private/var/mobile/Containers/Bundle/Application/2DAFF866-79B1-4569-A3D7-8A0D9A0ED9E5/Plot Gallery.app/Plot Gallery
  Reason: image not found

**Comment by eskroch** [comment]
This is new with iOS 8.3. I'll take a look.

**Comment by eschramm** [comment]
I don't know if it helps, but it sounds like with 8.3, the Framework is now throwing exceptions for nil as a referred view when using Auto-Layout - see http://mikeabdullah.net/nslayoutconstraint-nil-view-exception.html
