### ISSUE TITLE
ENABLE_STRICT_OBJC_MSGSEND=YES compilation failure on xcode 6.3

### ISSUE THREAD

**Issue by ngutman** [core-plot/core-plot#172]
Hi,
I'm using CorePlot 1.5.1 and getting the following compilation error:
  
    /Project/CorePlot/framework/Source/CPTAnimation.m:359:42: Too many arguments to function call, expected 0, have 3

Setting ENABLE_STRICT_OBJC_MSGSEND to NO specifically on CorePlot solves this.

Is the problem on my end?

**Comment by gcatellaniNL** [comment]
I wrote the following in a README in the project I'm working on in our company:

using CocoaPods 0.3.6 or higher sets the compiler-flag ENABLE_STRICT_OBJC_MSGSEND for all Pod-Projects. In conjunction with CorePlot < 2.0 this leads to compile errors in CorePlot. CorePlot 2.0 is currently in development and not yet ready to be used. So we either need to set this flag each time we use “pod install” or use an older CocoaPods version (< 0.3.6). As a temporary workaround you can set this flag to NO in the project settings of CorePlot. Once CorePlot 2.0 is released we will use that one and all will be good once and for all. Date of change: 25. March 2015

I would love for a simple maintenance-release addressing solely this issue (e.g. CorePlot 1.5.2) instead of having to wait for the 2.0. Especially as we need to run pod install a lot and then have to set the flag to NO again and again.

**Comment by eskroch** [comment]
If you're using CocoaPods, you can point your podfile at the Master branch.

    pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'

Release 1.6 will be out as soon as we squash a couple of remaining bugs. See issue #146.

**Comment by ngutman** [comment]
@eskroch awesome, thanks! looking forward for the release.

**Comment by veritech** [comment]
You can "monkey patch" this issue without pointing your Podfile (ie. still at 1.5.1) at the repo head by appending the below to your Podfile.

```
post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name.include? "CorePlot"
        config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
      end
    end
  end
end
```
