### ISSUE TITLE
How to short memory usage?

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#184]
In landscape mode when I drag the plot, it will lead graph reload which will mike a soaring cost of memory.
How can i solve this problem?
Thanks a lot.

**Comment by eskroch** [comment]
The plot will only load the data you tell it to. It won't reload during user interaction unless `-reloadData` is called. Reloading plot data when not necessary won't increase memory usage since the old data cache is thrown away, but it will reduce performance. You can use `-insertDataAtIndex:numberOfRecords:` and `-deleteDataInIndexRange:` to add and remove data points without reloading the whole dataset.

**Comment by Toanso** [comment]
Does reloadDataInIndexRange works?

**Comment by eskroch** [comment]
Yes, but that doesn't affect the overall memory usage of the plot. It lets you reload some of the plot data without changing the overall number of data points.

**Comment by Toanso** [comment]
can you describe more detail about insert or deleteDataIndexRange?

**Comment by eskroch** [comment]
`-deleteDataInIndexRange:` removes plot data that had previously been loaded by the plot. `-insertDataAtIndex:numberOfRecords:` tells the plot that new data is available and increases the total number of data points in the plot. The plot will request the new data points from the datasource using the usual methods. Any data previously loaded in the plot is left unchanged.
