### ISSUE TITLE
Multiple plots in Swift

### ISSUE THREAD

**Issue by Urash1ma** [core-plot/core-plot#188]
Hello! I am making an educational app for my career project and I am using your library (Saved my life! Thank you very much for adapting it to Swift!) to plot some data.
The fact is that I am in the need of plotting multiple data in the same plotspace. The data source is from user input's math functions that I operate and then I have to plot. I have been looking for examples to do this but I find them only in Objective-C (I just started learning Swift) and I don't really understand how the numberForPlot method works.
The arrays I have to plot are stored in an overall model, but I don't manage to access the data. I learned how to plot just one array of data from your example in Swift in the release 2.0. 
I hope you can help me with this...

Thanks a lot!

**Comment by eskroch** [comment]
Many of the example apps include multiple plots in a graph, but as you said, most are in Objective-C. You can have multiple plots in a plot space. Give each one a unique `identifier` and check it in the datasource methods so you know which plot is requesting data. With Swift's more powerful `switch` statement, you can use strings as identifiers and switch on the `plot.identifier` rather than building an if-else ladder like you have to do in Objective-C.
