### ISSUE TITLE
How to optimize performance and memory usage in landscape mode?

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#190]
I found in landscape mode when move and reload data, memory usage will increase to 200M on iPhone 6 plus, but only 60M on iPhone 5s with same scene, on iPhone 6 plus you can feel lag when move graph plots.

Any suggestion will be appreciative.

Thanks a lot.

**Comment by eskroch** [comment]
The screen on an iPhone 6 Plus has almost three times as many pixels as a 5S, so that explains the extra memory usage. It's also probably the cause of the performance problem. All of the usual Core Plot performance hints apply. For example, simplify the graph as much as you can. Set fills and line styles to `nil` if you don't need them so it can skip drawing them. If you use clear colors, it still has to run the drawing code for that element even though it doesn't affect the appearance of the graph. Use gradients sparingly. Make sure the axes are set up so they do not have too many grid lines or labels.
