### ISSUE TITLE
how to pull CurvedScatterPlot out as a independent uiview

### ISSUE THREAD

**Issue by kscorpio** [core-plot/core-plot#197]
in order to use it in other controller ，class CurvedScatterPlot  is couple to PlotItem

**Comment by kscorpio** [comment]
in addition  does release 1.0 support x64？

**Comment by eskroch** [comment]
The [latest release](https://github.com/core-plot/core-plot/releases/latest) is 1.6. If you're starting a new project, you should start with that one. Core Plot has supported 32- and 64-bit on the Mac since the beginning. Apple added 64-bit on iOS with the iPhone 5S in 2013. Core Plot release 1.5 is the first one that included 64-bit code on iOS.

**Comment by eskroch** [comment]
The `PlotItem` class takes care of setting up the hosting view. The subclasses (the demo plots) create the graph and add it to the hosting view. If you want to see everything together, look at some of the other example apps, e.g., the iPhone and iPad versions of CPTTestApp.

**Comment by kscorpio** [comment]
thanks , 
how can i get CurvedScatterPlot  from plot gallery, becauce it has many variable and methods from class PlotItem。
