### ISSUE TITLE
How to set the dynamics of Y axis

### ISSUE THREAD

**Issue by liumin007** [core-plot/core-plot#200]
How to set the dynamics of Y axis, when I refresh the data source, due to the differences in the data is big, therefore I must be re set every time the Y axis,

```objc
plotSpace.yRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(yAxisMin)
                                                length:CPTDecimalFromFloat(yAxisMax)]; 
plotSpace.globalYRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(0.5)
                                                      length:CPTDecimalFromFloat(yAxisMax)];
```

But this led to the Y axis disappeared, what should   do, can you give an example? Another problem, set the Y axis value, after the refresh data, the last time the value of the Y axis is not Disappear， thanks

**Comment by eskroch** [comment]
Once the global range is set, it will prevent changing the `yRange` to a range outside it. Set the global range to `nil`, update the `yRange` to the new value, and reset the global range to a range that includes the new `yRange`. You can always use the plot space method `-scaleToFitPlots:` to update the x- and y- ranges instead of computing the new ranges yourself.

**Comment by liumin007** [comment]
I used method- (void)barPlot:(CPTBarPlot *)plot barWasSelectedAtRecordIndex:(NSUInteger)idx withEvent:(UIEvent *)event   
![Uploading 3CA342B0-02F7-4728-8242-4465442338B7.png…]()
when I reloadData 
![Uploading 547035BC-E4C2-4B26-A664-6E56D7F28C39.png…]()
