### ISSUE TITLE
Animating change of values in bar charts

### ISSUE THREAD

**Issue by aenglund** [core-plot/core-plot#237]
I have a bar chart that present values based on a certain period of time. When the user changes the time period I want to change the values that the bar chart is showing by "adjusting" the values in an animated fashion. The effect I'm looking for is an growing or shrinking bar (independently on other bars).

From examples I've seen an animation can be added to the plot. However; By looking at the code for CPTBarPlot I understand that the bars gets drawn on to the layer in drawBarInContext:recordIndex:. Since each bar doesn't have their own layer, there is no possibility for me to animate the bars separately.

In one of the example graphs in the demo app, I can see that an animation is applied to a property in the BarChartItem, which reloads the graph each time it gets called with a new value. I was trying this out on my own app and it works OK on newer faster devices, but there is a lot of work on CPU causing an unpleasant experience on older devices.
So from what I can tell there is no way for me to achieve this effect with core plot.
Do you have any suggestions for me, or am I out of luck?

Thanks,

**Comment by eskroch** [comment]
As you noticed, each plot is its own layer. No matter how you choose to animate the bars, it will have to redraw the whole plot every frame. If you don't have too many bars, you could use a different plot for each one. That would make it possible to animate them individually.

The *AAPLot* example app animates the bar chart by animating the plot range. That doesn't solve your problem since it affects the whole plot, but it's another option.
