### ISSUE TITLE
Scatter plot data labels help needed

### ISSUE THREAD

**Issue by mpogra** [core-plot/core-plot#239]
Hello Eric,

I have been using core-plot since very beginning and I found it very flexible and feature reach, Thanks for such wonderful library that makes developers life easy. 

Recently I have been working on a different kind of graphs (please see the attachment) and was able to achieve the desired graphs using core plot even I was able to add full featured mouse over support in graphs. 

Now problem I am facing is for data labels for graph. By default data labels are shown for each data point and I changed it to only show for third point (my graph has just 4 points and these are like (0,0),(2,34),(38,34),(40,0)). (refer attachment). All four points have same data label so just showing for third point and it's being displayed but I want to make the data label to be in canter between second and third point. I have already tried by adding layer.paddingRight/paddingLeft etc but not working, even layer.position is not working.

Some how look's like to me that position (x, y) for data label are ignored by core plot and it always draws around the point. Any help will be appreciated to get it working as I need.

Also please note that I am not using CPTPlotSpaceAnnotation as that I use for Hover info. Below is code from dataLabelForPlot: recordIndex:. Changing x and y from 0 0 to any values does not work.
```
CPTLayer *layer = [[CPTLayer alloc] initWithFrame:CGRectMake(0,0, 300, 25)];
CPTTextLayer * newLayer = [[CPTTextLayer alloc] initWithText:textToShow  style:whiteText] ;
[layer addSublayer:newLayer];
        return layer;
```
Regards,
MP.
![screen shot 2015-10-28 at 7 27 32 am](https://cloud.githubusercontent.com/assets/10540903/10780292/da1bff30-7d61-11e5-8a5e-29220ac0d193.png)

**Comment by eskroch** [comment]
If you want the label centered between two data points, then a plot space annotation is the correct solution. You can have as many annotations on the graph as you want.

If you want the data label to always appear relative to one of the data points, use the plot's `labelOffset` to position it.

*Also answered on [StackOverflow](http://stackoverflow.com/questions/33383521).*

**Comment by mpogra** [comment]
Thanks Erik for the response. I will give it a try today. I am already using annotations for hover info.

**Comment by mpogra** [comment]
I tried but at first try wasn't able to get annotation working somehow, but then I see another issue that In my case graph height, i mean y axis value always changes (like in each 5 seconds) and annotation location does not update with that and require manual work to change location of anchor point. 

As I understand annotations are added respective to whole plot area frame not like data labels those are associated with specific plot. In my graph points are always going to be fix to be 4 and only y axis will change, x axis will remain same. I am looking for something like title of plot that moves with data point changes.

**Comment by eskroch** [comment]
There are two types of annotations:

* Plot space annotation: These are anchored to data coordinates defined by the plot space. They will move with the plots if the plot ranges of the plot space change for any reason, e.g., scrolling and/or zooming.

* Layer annotation: These are anchored to a particular part of the graph (all of which are Core Animation layers). They stay anchored to the same spot even if the plots move underneath due to changes in the plot space.

Annotations of either type can be attached to most parts of a graph, including plots, the plot area, and the graph itself. See the inheritance diagram in the [CPTAnnotationHostLayer docs](http://core-plot.github.io/MacOS/interface_c_p_t_annotation_host_layer.html) to see all of the subclasses that support annotations.
