### ISSUE TITLE
dataSource not available with xCode version 7.3

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#269]
After updated xCode latest version (7.3). There is an error with core plot datasource.
(Previous version its worked.)

> datasource not available

this is original 
`@property (nonatomic, readwrite, cpt_weak_property) __cpt_weak id<CPTPlotDataSource> dataSource;`
and i just remove __cpt_weak it worked.
`@property (nonatomic, readwrite, cpt_weak_property)  id<CPTPlotDataSource> dataSource;`
i don't know can i remove __cpt_weak.
@eskroch

**Comment by eskroch** [comment]
What version of Core Plot are you using? The latest version has this declaration:

     @property (nonatomic, readwrite, cpt_weak_property, nullable) cpt_weak id<CPTPlotDataSource> dataSource;

Note `cpt_weak` vs. `__cpt_weak`.

**Comment by declareerror** [comment]
coreplot 2.0  downloades from release

**Comment by euroboy** [comment]
Same problem. version 2.0, XCode 7.3

**Comment by declareerror** [comment]
`#if CPT_SDK_SUPPORTS_WEAK
#define __cpt_weak        
#define cpt_weak_property weak
#else
#if __clang__ && (__clang_major__ >= 3)
#define __cpt_weak __unsafe_unretained
#else
#define __cpt_weak
#endif
#define cpt_weak_property assign
#endif`

i modified your code with my code its worked. but i don't this is the best way to fix this problem.
and this is dataSource property 
`@property (nonatomic, readwrite, cpt_weak_property) __cpt_weak id<CPTPlotDataSource> dataSource;`
@eskroch

**Comment by eskroch** [comment]
Make sure the app is pointed at the right headers. The 2.0 release has the new declaration (with out the leading underscores) I posted above. Is this iOS or Mac? Are you using the release package or building from source?

**Comment by declareerror** [comment]
I used IOS version. using from release package. Still have an error.

**Here is CPTDefinitions.h screen short.**
![screen shot 2016-03-23 at 08 37 20](https://cloud.githubusercontent.com/assets/5284788/13973167/8c3d9a32-f0d2-11e5-8ef5-3e247a62b079.png)

**Link binary in my project**
![screen shot 2016-03-23 at 08 36 40](https://cloud.githubusercontent.com/assets/5284788/13973168/8c46938a-f0d2-11e5-8c0c-12f06acb5cfc.png)
**Data source property**
![screen shot 2016-03-23 at 08 37 32](https://cloud.githubusercontent.com/assets/5284788/13973166/8bdc8788-f0d2-11e5-8c80-09df1ee4db1a.png)
**Build error**
![screen shot 2016-03-23 at 08 33 18](https://cloud.githubusercontent.com/assets/5284788/13973138/4196ac44-f0d2-11e5-8cb1-6cc035572062.png)

Do you have any ideas what wrong? Thank you.
@eskroch

**Comment by eskroch** [comment]
The headers are right now. Where are those build errors? In your app? Make sure those files import the Core Plot headers (`CorePlot-CocoaTouch.h`).

**Comment by declareerror** [comment]
I imported already. 
![screen shot 2016-03-23 at 09 16 07](https://cloud.githubusercontent.com/assets/5284788/13973672/ea857894-f0d7-11e5-9708-4b256031a88d.png)
@eskroch

**Comment by malikmani** [comment]
I am also facing this issue 'dataSource is unavailable' due to the ARC is disabled in my Project.

So If change this original line (CPTDefiniations.h):
`#define cpt_weak        __weak`
to:
`#define cpt_weak  `
It compiled and worked fine.Is this the correct way to resolve this issue?

CorePlot v2.0 is currently been used in my project.

**Comment by eskroch** [comment]
Weak properties require automatic reference counting. Turning on ARC in the files that reference any Core Plot weak properties will eliminate the error.

I know how, but I'm not sure if I can safely turn off the weak setting when compiling client apps without ARC. I need to research that further.

**Comment by eskroch** [comment]
Research info: Mike Ash has a good overview of [ARC](https://www.mikeash.com/pyblog/friday-qa-2011-09-30-automatic-reference-counting.html).

**Comment by gyratorycircus** [comment]
At least for the `dataSource` property, it doesn’t look like the `cpt_weak` is serving a purpose. If the ivar were explicitly defined, then it would be necessary to prepend the ivar with a `__weak` to use with a weak property. But since its synthesized, the ivar will automatically be created as weak. Actually, Mike Ash also discusses this in the Properties section of the article. I've also never seen `__weak` used at that location in the property declaration -- is this allowed?

**Comment by eskroch** [comment]
It may be redundant, but it's obviously allowed. Core Plot has been around a long time. `cpt_weak` may be a holdover from before we could use automatically synthesized ivars.

The big unanswered question I have is how does non-ARC client code deal with a `weak` property. Since Core Plot is compiled with ARC, these are zeroing weak references. Non-ARC code will see them as `unsafe_unretained` which is similar, except the compiler won't expect the automatic zeroing behavior which could cause problems in optimized code.

**Comment by gyratorycircus** [comment]
While it may be allowed, its redundant in the property declaration, and causing a compiler error. Removing the `cpt_weak` corrects the error and does not change the memory management of a property with a synthesized ivar.

**Comment by euroboy** [comment]
@eskroch I don't see this fix after installing Core Plot via CocoaPods (pod 'CorePlot', '~> 2.0'). 
How to get latests commits via pods? Thanks.

**Comment by iDevelopper** [comment]
Why some users like me does not issue this problem? Xcode 7.3 (pod 'CorePlot', '~> 2.0') too.

**Comment by eskroch** [comment]
Use this line in the pod file to get the latest code from the Master branch:

    pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'
