### ISSUE TITLE
[CPTXYAxis setOrthogonalPosition] unrecognized selector sent to instance

### ISSUE THREAD

**Issue by fireup** [core-plot/core-plot#273]
I just upgraded to CorePlot 2.0 from 1.5, and changed the old method `x.orthogonalCoordinateDecimal = CPTDecimalFromDouble(0);` to `x.orthogonalPosition          = @(0.0);`. Then I got this unrecognized selector error.  Is there anything I'm doing wrong?

I'm using CocoaPods, but not "use_frameworks"
`pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'`
 and `#import <CorePlot/ios/CorePlot.h>`

**Comment by eskroch** [comment]
Have you tried doing a clean build of the app?

**Comment by fireup** [comment]
Yes I have, multiple times.

**Comment by fireup** [comment]
could it because I've set `platform :ios, '7.0'` in my podfile?

**Comment by eskroch** [comment]
The iOS deployment target for Core Plot 2.0 static library builds is iOS 6.0 so that isn't it. iOS frameworks require iOS 8.0, but that's a platform limitation.

Make sure the pod libraries get a clean build, too. You might have to clear Xcode's derived data folder to remove any old linker products or caches that are being used by mistake.

**Comment by fireup** [comment]
Clean build, clearing derived data, tried them all. 
But then I figured I'd give it a try with the platform settings, so I did the following and don't know why it just fixed...

1) `platform :ios, '8.0'`
2) `pod install`
built and ran without error

3) set it back to `platform :ios, '7.0'`
4) `pod install`
again, ran without error...

Thank you for your response. Thought I'd spend some time on getting a good understanding of cocoapods... :)
