### ISSUE TITLE
Multiple axis in Coreplot ?

### ISSUE THREAD

**Issue by NANDEESHKUMAR** [core-plot/core-plot#279]
I have created additional axis and my plot is looking like this.
![8686b4b6-0bcb-11e6-80fe-b78b718f427c](https://cloud.githubusercontent.com/assets/18665100/14934408/0f50d4e4-0eaf-11e6-806e-5f769a9b28bf.png)
What I want is that the Axis to be shown on the top of the plot but in the above graph the axis is behind the plot.

How I can achieve it?

**Comment by eskroch** [comment]
The easiest way would be to use scatter plots to draw the horizontal lines instead of axes. Add them to the graph after the bar plot and they will be drawn on top. You can use the plot area [`topDownLayerOrder `](http://core-plot.github.io/iOS/interface_c_p_t_plot_area.html#a506fba7759eff65695ca5a7be253176f) property to move all of the axis lines in front of the plots.

**Comment by iDevelopper** [comment]
@NANDEESHKUMAR ,then just do that:

    [graph setTopDownLayerOrder:@[@(CPTGraphLayerTypeAxisLines)]];

**Comment by iDevelopper** [comment]
@eskroch , Hi

How to set background color of CPTAxisTitle/CPTTextStyle?

Is it possible? Or should we use annotation with CPTTextLayer?

![2016-05-01_12-44-33](https://cloud.githubusercontent.com/assets/1782450/14941447/16bcd76c-0f9c-11e6-933f-434e76fc85a8.png)

**Comment by eskroch** [comment]
Use an annotation and set the `fill` of the `contentLayer`.

**Comment by iDevelopper** [comment]
@eskroch , nickel, thanks !
![2016-05-01_15-33-14](https://cloud.githubusercontent.com/assets/1782450/14942067/2c9ebf76-0fb2-11e6-9a6f-79730721b82e.png)
