### ISSUE TITLE
Can't assign CPTBarPlotDelegate 

### ISSUE THREAD

**Issue by grosch** [core-plot/core-plot#292]
Using the 2.1 version and Xcode 8 Beta 3 via a pod install there's no way to assign the 'delegate' of a CPTBarPlot as it's complaining 

> Cannot assign value of type 'MyClass?' to type 'CALayerDelegate?'

The class implements the CPTBarPlotDelegate.  I'm *guessing* the problem is that CALayerDelegate roots from NSObject, whereas the CPTBarPlotDelegate roots from NSObjectProtocol.

I know Xcode 8 isn't fully released yet, but I figured you'd want to know about this issue sooner rather than later.

**Comment by iDevelopper** [comment]
Please see #291

**Comment by eskroch** [comment]
Use the following line in your pod file to get the `release-2.2` branch:

    pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git', :branch => 'release-2.2'

**Comment by sergii-frost** [comment]
Hi, 
I am using Xcode 8 and CorePlot v2.2 and I am subclassing CPTBarPlot to have extended behaviour.

And currently I am facing error like `no known instance method for selector 'barPlot:barWasSelectedAtRecordIndex:'` in this part of code: 

```
if (self.delegate && [self.delegate respondsToSelector:@selector(barPlot:barWasSelectedAtRecordIndex:)]) {
    [self.delegate barPlot:self barWasSelectedAtRecordIndex:...];
}
```

As a workaround I've changed my code to be like: 

```
if (self.delegate && [self.delegate conformsToProtocol:@protocol(CPTBarPlotDelegate)] && [self.delegate respondsToSelector:@selector(barPlot:barWasSelectedAtRecordIndex:)]) {
    id<CPTBarPlotDelegate> delegate = (id<CPTBarPlotDelegate>)self.delegate;
    [delegate barPlot:self barWasSelectedAtRecordIndex:DESELECTED_INDEX];
}
```

I am not sure if this is due to more strict rules in Xcode 8 (as same code worked fine in Xcode 6.x ,7.x for 2 years), or this can be fixed in the CorePlot somehow.

**Comment by eskroch** [comment]
@sergii-frost Correct, this is due to some changes in the compiler and SDKs with Xcode 8. You have a good solution.
