### ISSUE TITLE
 interpolation CPTScatterPlotInterpolationCurved not perform correct Curve

### ISSUE THREAD

**Issue by guoguoli** [core-plot/core-plot#295]
when use CPTScatterPlot I set it's interpolation CPTScatterPlotInterpolationCurved, I found some strange thing ,don't know how to describe it I show you the pictures
when I set interpolation CPTScatterPlotInterpolationCurved it looks like this,[https://github.com/guoguoli/pictures/blob/master/%20CPTScatterPlotInterpolationCurved.png](url)
when I set  interpolation CPTScatterPlotInterpolationLinear it looks like this,[https://github.com/guoguoli/pictures/blob/master/CPTScatterPlotInterpolationLinear.png](url)

**Comment by DD-P** [comment]
Your links appear to be invalid.

**Comment by koenvanderdrift** [comment]
You can also go here to see them: 

https://github.com/guoguoli/pictures

**Comment by guoguoli** [comment]
@DD-P I don't know why it is invalid，but  you can see them  as **koenvanderdrift**  said

**Comment by eskroch** [comment]
What version of Core Plot are you using? Release 2.1 added some additional options for curved scatter plots.

Use the `curvedInterpolationOption` property to change the interpolation algorithm used to smooth the curve. Since your data has sharp corners, try `CPTScatterPlotCurvedInterpolationCatmullRomCentripetal`. If that isn't satisfactory, try some of the others.
