### ISSUE TITLE
Create crosshair line using axis but its underneath graph.

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#338]
I create crosshair line by using CPTXYAxis. it's work but its still underneath area graph.
![teampaper snap_2017-05-12 15-55-58](https://cloud.githubusercontent.com/assets/5284788/25991054/24e0b706-372c-11e7-9c18-1f6af9748173.png)
I'd like its stay above all plots. How can i bring crosshair line above all plots in these graph.

Thank you.

**Comment by eskroch** [comment]
You can reorder the various Core Animation layers used to draw the graph using the [`topDownLayerOrder`](http://core-plot.github.io/iOS/interface_c_p_t_plot_area.html#a506fba7759eff65695ca5a7be253176f) property. Another solution is to use a scatter plot to draw the crosshairs instead of an axis. There's an example of this technique in the Mac version of the *CPTTestApp* example app.

**Comment by declareerror** [comment]
That's work @eskroch Thank you. 
You save my time.
