### ISSUE TITLE
Get axis draw points on screen

### ISSUE THREAD

**Issue by anuragajwani** [core-plot/core-plot#370]
Hi @eskroch 

First of all I really appreciate the work you are doing here, thanks for this library!

I want to draw a dashed line over a bar plot, I have been able to render the bar chart and now I would like to know where each coordinate within the bar relates to the screen. i.e. lets say I have a y axis that goes from 0 to 10 I would like to get the x and y positions within the screen of 8 where the line starts and also get the x position of where the x axis ends (I am trying to draw a dashed line). So far I have been playing with `XYAxis` (from `XYAxisSet`) and read its `frame` property, both x and y axis return the same.

```
Optional((0.0, 0.0, 375.0, 200.5))
Optional((0.0, 0.0, 375.0, 200.5))
```

Any pointers where should I be looking to get the correct values of where the axis are laid out on screen?

Thanks in advanced,
Anurag

**Comment by eskroch** [comment]
Depending on what you want to do, the easiest way to draw a line on the graph is to use a scatter plot, or even another axis if you only need a horizontal or vertical line. Otherwise, use the plot space to convert between data values and the graph's coordinate system. Use the `-(CGPoint)plotAreaViewPointForPlotPoint:` or related methods.
