### ISSUE TITLE
custom majorTick

### ISSUE THREAD

**Issue by liumin007** [core-plot/core-plot#379]
for custom majorTick,  Just like the picture url, what should I do  
![default](https://user-images.githubusercontent.com/8297744/39391573-5825cf6e-4ad8-11e8-90e6-2f47a54fa216.png)

**Comment by eskroch** [comment]
Use the [`majorTickLength`](http://core-plot.github.io/iOS/interface_c_p_t_axis.html#a1b364b8af8a412f91c4e8d957b6703d9) to change the length of the tick lines and [`majorTickLineStyle `](http://core-plot.github.io/iOS/interface_c_p_t_axis.html#a929d48e2e177d2f154c3ab7618632ae3) to change the line style (color, line width, line cap, etc.).

**Comment by liumin007** [comment]
![11525316158_ pic](https://user-images.githubusercontent.com/8297744/39558372-a58d4642-4ec0-11e8-8fa7-3abbd2eebfa9.jpg)   
![2018-05-03 10 57 47](https://user-images.githubusercontent.com/8297744/39558397-dbae5202-4ec0-11e8-9533-ed8e282d3b85.png)
![2018-05-03 10 57 37](https://user-images.githubusercontent.com/8297744/39558398-dd74f078-4ec0-11e8-87c9-d18732bdc07d.png)   
How to let it be a circle?

**Comment by eskroch** [comment]
I don't think you can get a circle shape for the tick marks. The round line cap is not perfectly circular—you can always see part of the straight edge of the line. It looks like you also have a clipping issue along the edge of the graph that might be solved with some padding or changing the `tickDirection` so the tick marks extend into the graph rather than straddling the axis line.
